spring:
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/spring
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update


server:
  port: 9090

auth:
  server:
    base:
      url: http://localhost:8080

jwt:
  signing:
    key: ymLTU8rq83j4fmJZj60wh4OrMNuntIj4fmJ
















