spring:
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/spring
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update